### ISSUE TITLE
URL Generation with Dynamic Domain: Potential Redundancy in hello.${config.helloDomain}

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [hellocoop/packages-js#43]
```typescript
const HELLO_DOMAIN = process.env.HELLO_DOMAIN as string || 'hello.coop';

config.helloDomain = HELLO_DOMAIN;

const url = `https://hello.${config.helloDomain}/invite?${new URLSearchParams(request as any)}`;
```

Would this create a URL like `https://hello.hello.coop/invite?`?

**Comment by rohanharikr** [comment]
Thank you for pointing this out - this was a bug.
`url` should have be `https://wallet.${config.helloDomain}/invite?${new URLSearchParams(request as any)}`;
Fixed with https://github.com/hellocoop/packages-js/commit/5ccefdc96ee247dbeae4ac8a3c5282903b62b896
